# Generated by Django 5.2.8 on 2025-11-28 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for the task', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the task', max_length=10)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
